# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_manager', '0004_auto_20170522_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_manager.Folder')
        ),
    ]
